# Dataset settings
DATA:
    BATCH_SIZE: 256
    DIR: ~/workspace/datasets/covidx
    IMG_SIZE: 256
    INTERPOLATION: bicubic
    PIN_MEMORY: True
    NUM_WORKERS: 16

# Model settings
MODEL:
    ARCH: resnet18
    NUM_CLASSES: 3
    LABEL_SMOOTHING: 0.1
    RESUME: ''
    
# Self-supervised Learning settings    
SSL:
    PROJECTION_HIDDEN_SIZE: 512
    PROJECTION_SIZE: 128
    USE_MOMENTUM: True
    MOVING_AVERAGE_DECAY: 0.99

# Augmentation settings
AUG:
    LEVEL: 4
    # AutoAugment Policy
    AUTO_AUGMENT: rand-m9-mstd0.5-inc1
    # Random erase prob, mode, count
    REPROB: 0.25
    REMODE: pixel
    RECOUNT: 1
    # Mixup alpha
    MIXUP: 0.8
    # Cutmix alpha
    CUTMIX: 1.0
    CUTMIX_MINMAX: null
    MIXUP_PROB: 1.0
    # Probability of switching to cutmix when both mixup and cutmix enabled
    MIXUP_SWITCH_PROB: 0.5
    MIXUP_MODE: batch
    
# Train settings
TRAIN:
    START_EPOCH: 0
    EPOCHS: 20
    WARMUP_EPOCHS: 0
    WEIGHT_DECAY: 0.0
    BASE_LR: 10.0
    WARMUP_LR: 0.5
    MIN_LR: 0.000001
    CLIP_GRAD: 5.0
    
    TWOCROP: false
    
    AUTO_RESUME: True
    ACCUMULATION_STEPS: 0
    # Whether to use gradient checkpointing to save memory
    # could be overwritten by command line argument
    USE_CHECKPOINT: False
    
    # Scheduler settings
    LR_SCHEDULER:
        NAME: cosine
        # Epoch interval to decay LR, used in StepLRScheduler
        DECAY_EPOCHS: 20
        DECAY_RATE: 0.1
        
    # Optimizer settings
    OPTIMIZER:
        NAME: sgd
        EPS: 0.00000001
        BETAS: [0.9, 0.999]
        MOMENTUM: 0.9
        NESTEROV: True

LINEAR_EVAL: True
SSL_PRETRAIN: True
        
TEST:
    CROP: True
    
# Other settings
AMP_OPT_LEVEL: 'O1'
OUTPUT: './checkpoints/SSL'
TAG: 'default'
SAVE_FREQ: 1
PRINT_FREQ: 10
SEED: 0
LOCAL_RANK: 0


LINEAR_EVAL: True



    
    

    